spring:
  datasource:
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: ${DEV_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    url: ${DEV_DB_URL}
    password: ${DEV_DB_PASSWORD}
    user: ${DEV_DB_USERNAME}

server:
  port: 8081

app:
  isTest: true

